version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install prototool
          command:
            curl -sSL https://github.com/uber/prototool/releases/download/v1.0.0/prototool-$(uname -s)-$(uname -m) -o ./prototool &&
            chmod +x ./prototool
      - run:
          name: Format protobuf - write a diff instead
          command: ./prototool format -d protobuf
