version: 2
jobs:
  "protobuf":
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install prototool
          command:
            curl -sSL https://github.com/uber/prototool/releases/download/v1.0.0/prototool-$(uname -s)-$(uname -m) -o ./prototool &&
            chmod +x ./prototool
      - run:
          name: Format protobuf - write a diff instead
          command: ./prototool format -d protobuf

  "push-subscription-test":
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/nokamoto/webpush-101
    steps:
      - checkout
      - run:
          name: Format go - display diffs instead of rewriting files
          command: test -z "$(gofmt -l ./webpush-go/push-subscription)"
      - run:
          name: Check coding style
          command:
            go get -u golang.org/x/lint/golint && 
            golint -set_exit_status ./webpush-go/push-subscription
      - run:
          name: Run test
          command: 
            go get -u github.com/golang/dep/cmd/dep &&
            dep ensure -vendor-only=true &&
            go test ./webpush-go/push-subscription

  "webpush-test":
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/nokamoto/webpush-101
    steps:
      - checkout
      - run:
          name: Format go - display diffs instead of rewriting files
          command: test -z "$(gofmt -l ./webpush-go/webpush)"
      - run:
          name: Check coding style
          command:
            go get -u golang.org/x/lint/golint && 
            golint -set_exit_status ./webpush-go/webpush
      - run:
          name: Run test
          command: 
            go get -u github.com/golang/dep/cmd/dep &&
            dep ensure -vendor-only=true &&
            go test ./webpush-go/webpush

  "webpush-lib-test":
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/nokamoto/webpush-101
    steps:
      - checkout
      - run:
          name: Format go - display diffs instead of rewriting files
          command: test -z "$(gofmt -l ./webpush-go/webpush-lib)"
      - run:
          name: Check coding style
          command:
            go get -u golang.org/x/lint/golint && 
            golint -set_exit_status ./webpush-go/webpush-lib
      - run:
          name: Run test
          command: 
            go get -u github.com/golang/dep/cmd/dep &&
            dep ensure -vendor-only=true &&
            go test ./webpush-go/webpush-lib

  "front-test":
    docker:
      - image: openjdk:8
    steps:
      - restore_cache:
          key: sbt-cache
      - checkout
      - run:
          name: Get sbt
          command: 
            curl -Ls https://git.io/sbt > ./sbt && 
            chmod 0755 ./sbt
          working_directory: webpush-scala/front
      - run:
          name: Format scala
          command: ./sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test
          working_directory: webpush-scala/front
      - run:
          name: Run test
          command: ./sbt test
          working_directory: webpush-scala/front
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  build:
    jobs:
      - "protobuf"
      - "push-subscription-test"
      - "webpush-test"
      - "webpush-lib-test"
      - "front-test"
